"""followers

Revision ID: 08494244b6e0
Revises: 0bba5ddb3a95
Create Date: 2020-04-24 18:21:11.821799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08494244b6e0'
down_revision = '0bba5ddb3a95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
